general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'SAP Presales Cloud (NEO/FOUNDRY)_sappsbr'
      space: 'QA'
      credentialsId: 'CF_CREDENTIALSID'